import DynamicTableOrganism from "../../organisms/DynamicTable";

export default function DashboardTableConfig(props) {
  return <DynamicTableOrganism {...getConfig(props)} />;
}

const getConfig = ({ zone, role, ...rest }) => {
  const data = [
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Normal",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Normal",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Normal",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
    {
      requestID: "REQ-1443434004",
      region: "GHQ",
      submissionDate: "23-03-2024",
      approvedDate: "23-03-2024",
      prType: "Urgent",
      vendorName: "Accenture NV",
      vendorNumber: "321456",
      poTitle: "Acuvate santhosh billing",
      currency: "INR",
      poValue: "INR",
      status: "Pending Approval",
    },
  ];

  let config = {};
  switch (`${zone}/${role}`) {
    default:
      config = {
        columns: [
          {
            accessorKey: "requestID",
            header: "Request ID",
            size: 50,
          },
          {
            accessorKey: "region",
            header: "Region",
            size: 10,
          },
          {
            accessorKey: "submissionDate",
            header: "Submission Date",
            size: 10,
          },
          {
            accessorKey: "approvedDate",
            header: "Approved Date",
            size: 10,
          },
          {
            accessorKey: "prType",
            header: "PR Type",
            size: 10,
          },
          {
            accessorKey: "vendorName",
            header: "Vendor Name",
            size: 10,
          },
          {
            accessorKey: "vendorNumber",
            header: "Vendor Number",
            size: 10,
          },
          {
            accessorKey: "poTitle",
            header: "PO Title",
            size: 10,
          },
          {
            accessorKey: "currency",
            header: "Currency",
            size: 10,
          },
          {
            accessorKey: "poValue",
            header: "PO Value",
            size: 10,
          },
          {
            accessorKey: "status",
            header: "Status",
            size: 10,
          },
        ],
        data: data || [],
      };
      break;
  }

  return {
    columnData: config?.columns,
    data: config?.data,
    showExport: true,
  };
};
